### ISSUE TITLE
description of raw data fields

### ISSUE THREAD

**Issue by mdscheuerell** [veggerk/Puget-Sound-shrimp-paper#2]
We need to describe the contents of each of the data fields (columns) in the raw data file. At present, these are column headers (`X1` is a temporary placeholder because there is no column header in the raw data file):

```
X1 = col_double()
year = col_double()
X = col_double()
time.year.depth = col_character()
date = col_character()
time.category = col_character()
depth.target..m. = col_double()
group = col_character()
common.name = col_character()
genus.species = col_character()
genus.species.updated = col_character()
number = col_double()
CPUE.m2.of.net = col_double()
shrimp.cpue = col_double()
avg.oni.previous.12.months = col_double()
el.nino.la.nina = col_character()
```

I'd suggest we do this as either a separate metadata file, or include a description in the data reading/munging script `01_data-cleaning.r`.

**Comment by veggerk** [comment]
done
